name: pull-request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  build-dotnet:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      NUGET_XMLDOC_MODE: ''

    steps:
      - uses: actions/Checkout@v4
      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          dotnet-quality: ga
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      
      - run: >-
          dotnet build
          --configuration Debug
          -p:ContinuousIntegrationBuild=true

      - run: >-
          dotnet test
          --configuration Debug
          --logger trx
          --collect:"XPlat Code Coverage"
      
      - uses: bibipkins/dotnet-test-reporter@v1.3.3
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-path: '**/TestResults/**/*.trx'
          coverage-path: '**/TestResults/**/coverage.cobertura.xml'
          coverage-type: cobertura
